apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: collector
  name: collector
spec:
  containers:
  - image: cyberdojo/collector
    name: cyber-dojo-collector
    resources:
      limits:
        memory: "1073741824"
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: collector-claim0
  restartPolicy: OnFailure
  volumes:
  - name: collector-claim0
    persistentVolumeClaim:
      claimName: collector-claim0
status: {}
