apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: differ
  name: differ
spec:
  containers:
  - image: cyberdojo/differ
    name: cyber-dojo-differ
    resources:
      limits:
        memory: "1073741824"
    volumeMounts:
    - mountPath: /tmp
      name: differ-tmpfs0
  restartPolicy: OnFailure
  volumes:
  - emptyDir:
      medium: Memory
    name: differ-tmpfs0
status: {}
