apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  containers:
  - image: cyberdojo/nginx
    name: cyber-dojo-nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "52428800"
  restartPolicy: OnFailure
status: {}
