apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: runner-processful
  name: runner-processful
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: runner-processful
    spec:
      containers:
      - image: cyberdojo/runner_processful
        name: cyber-dojo-runner-processful
        resources:
          limits:
            memory: "2147483648"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: runner-processful-claim0
        - mountPath: /tmp
          name: runner-processful-tmpfs0
      restartPolicy: Always
      volumes:
      - name: runner-processful-claim0
        persistentVolumeClaim:
          claimName: runner-processful-claim0
      - emptyDir:
          medium: Memory
        name: runner-processful-tmpfs0
status: {}
