apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: starter
  name: starter
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 4527
    targetPort: 4527
  selector:
    io.kompose.service: starter
status:
  loadBalancer: {}
