apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: storer
  name: storer
spec:
  containers:
  - env:
    - name: CYBER_DOJO_KATAS_ROOT
    image: cyberdojo/storer
    name: cyber-dojo-storer
    resources:
      limits:
        memory: "2147483648"
    volumeMounts:
    - mountPath: /tmp
      name: storer-tmpfs0
  restartPolicy: OnFailure
  volumes:
  - emptyDir:
      medium: Memory
    name: storer-tmpfs0
status: {}
