apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
  - env:
    - name: CYBER_DOJO_HOME
    image: cyberdojo/web
    name: cyber-dojo-web
    resources:
      limits:
        memory: "2147483648"
  restartPolicy: OnFailure
status: {}
