apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipper
  name: zipper
spec:
  containers:
  - image: cyberdojo/zipper
    name: cyber-dojo-zipper
    resources:
      limits:
        memory: "52428800"
    volumeMounts:
    - mountPath: /tmp
      name: zipper-tmpfs0
  restartPolicy: OnFailure
  volumes:
  - emptyDir:
      medium: Memory
    name: zipper-tmpfs0
status: {}
